// Seed data for products
// This file is only used on first load to populate LocalStorage

var SEED_PRODUCTS = [
    {
        id: 1,
        shopId: 5,
        name: "iPhone 15 Pro Max",
        price: 1199,
        oldPrice: 1499,
        image: "../asset/img/home/ip15PM.webp",
        category: "smartphone",
        rating: 4.8,
        reviews: 342,
        stock: 25,
        description: "The most powerful iPhone ever with A17 Pro chip, titanium design, and 48MP camera system.",
        adminStatus: "approved",
        createdAt: "2025-09-22"
    },
    {
        id: 2,
        shopId: 6,
        name: "Samsung Galaxy S24 Ultra",
        price: 1299,
        oldPrice: 1599,
        image: "https://cdn2.fptshop.com.vn/unsafe/512x0/filters:format(webp):quality(75)/2024_1_27_638419500119790990_samsung-galaxy-s24-ultra-xam-4.png",
        category: "smartphone",
        rating: 4.7,
        reviews: 287,
        stock: 18,
        description: "Galaxy AI powered flagship with S Pen, 200MP camera, and titanium frame.",
        adminStatus: "approved",
        createdAt: "2025-01-17"
    },
    {
        id: 3,
        shopId: 8,
        name: "Google Pixel 8 Pro",
        price: 999,
        oldPrice: 1299,
        image: "../asset/img/home/pixel8.png",
        category: "smartphone",
        rating: 4.6,
        reviews: 215,
        stock: 30,
        description: "Google's smartest phone with Tensor G3 chip and advanced AI photography features.",
        adminStatus: "approved",
        createdAt: "2025-10-04"
    },
    {
        id: 4,
        shopId: 5,
        name: "Apple Watch Ultra",
        price: 799,
        oldPrice: 999,
        image: "https://cdn.tgdd.vn/Products/Images/7077/329717/s16/apple-watch-ultra-2-gps-cellular-49mm-vien-titanium-day-ocean-den-650x650.png",
        category: "wearables",
        rating: 4.9,
        reviews: 412,
        stock: 12,
        description: "The most rugged Apple Watch with 49mm titanium case, precision GPS, and 36-hour battery.",
        createdAt: "2025-09-22"
    },
    {
        id: 5,
        shopId: 6,
        name: "Samsung Galaxy Watch 6",
        price: 399,
        oldPrice: 599,
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/m/sm-r930_003_l_perspective_graphite_2_1.png",
        category: "wearables",
        rating: 4.6,
        reviews: 189,
        stock: 40,
        description: "Stylish smartwatch with BioActive sensor, sleep coaching, and Wear OS.",
        createdAt: "2025-07-26"
    },
    {
        id: 6,
        shopId: 8,
        name: "Dell XPS 15",
        price: 1699,
        oldPrice: 1999,
        image: "https://www.laptopvip.vn/images/ab__webp/detailed/31/notebook-xps-15-9530-t-black-galle~1-0g9i-c1-www.laptopvip.vn-1683083662.webp",
        category: "laptops",
        rating: 4.7,
        reviews: 226,
        stock: 15,
        description: "Premium 15-inch laptop with InfinityEdge display, 13th Gen Intel Core, and NVIDIA graphics.",
        createdAt: "2025-03-15"
    },
    {
        id: 7,
        shopId: 5,
        name: "MacBook Air M3",
        price: 1399,
        oldPrice: 1599,
        image: "https://cdsassets.apple.com/live/7WUAS350/images/tech-specs/mba_15_m3_2024_hero.png",
        category: "laptops",
        rating: 4.8,
        reviews: 378,
        stock: 22,
        description: "Supercharged by M3 chip with 18-hour battery life and Liquid Retina display.",
        createdAt: "2025-03-08"
    },
    {
        id: 8,
        shopId: 8,
        name: "ASUS ROG Zephyrus G14",
        price: 1499,
        oldPrice: 1799,
        image: "https://cdn2.fptshop.com.vn/unsafe/512x0/filters:format(webp):quality(75)/2024_1_15_638406886543034665_asus-rog-zephyrus-g14-ga403u-1.jpg",
        category: "laptops",
        rating: 4.7,
        reviews: 244,
        stock: 10,
        description: "Ultra-slim gaming laptop with AMD Ryzen 9, RTX 4060, and AniMe Matrix display.",
        createdAt: "2025-04-20"
    },
    {
        id: 9,
        shopId: 7,
        name: "Sony WH-1000XM5",
        price: 329,
        oldPrice: 399,
        image: "../asset/img/home/sonyWH.png",
        category: "audio",
        rating: 4.8,
        reviews: 512,
        stock: 50,
        description: "Industry-leading noise cancellation with crystal clear hands-free calling.",
        createdAt: "2025-05-10"
    },
    {
        id: 10,
        shopId: 9,
        name: "Bose QuietComfort Ultra",
        price: 349,
        oldPrice: 429,
        image: "../asset/img/home/boseQuiet.jpg",
        category: "audio",
        rating: 4.7,
        reviews: 294,
        stock: 35,
        description: "Immersive spatial audio with world-class noise cancellation and all-day comfort.",
        createdAt: "2025-09-14"
    },
    {
        id: 11,
        shopId: 9,
        name: "JBL Charge 5",
        price: 149,
        oldPrice: 199,
        image: "../asset/img/home/jblCharge.jpg",
        category: "audio",
        rating: 4.5,
        reviews: 318,
        stock: 60,
        description: "Portable Bluetooth speaker with powerful bass, IP67 waterproof, and 20-hour battery.",
        createdAt: "2025-06-01"
    },
    {
        id: 12,
        shopId: 9,
        name: "Canon EOS R50",
        price: 879,
        oldPrice: 999,
        image: "../asset/img/home/canonEOS.jpg",
        category: "cameras",
        rating: 4.6,
        reviews: 141,
        stock: 20,
        description: "Compact mirrorless camera with 24.2MP sensor, 4K video, and subject detection AF.",
        adminStatus: "rejected",
        createdAt: "2025-02-28"
    },
    {
        id: 13,
        shopId: 7,
        name: "Sony Alpha A7 IV",
        price: 2299,
        oldPrice: 2599,
        image: "../asset/img/home/sonyA7.jpg",
        category: "cameras",
        rating: 4.9,
        reviews: 187,
        stock: 8,
        description: "Full-frame hybrid camera with 33MP sensor, real-time Eye AF, and 4K 60p video.",
        createdAt: "2025-01-10"
    },
    {
        id: 14,
        shopId: 9,
        name: "GoPro HERO12 Black",
        price: 399,
        oldPrice: 499,
        image: "../asset/img/home/goProHero12.png",
        category: "cameras",
        rating: 4.6,
        reviews: 263,
        stock: 45,
        description: "Waterproof action camera with 5.3K video, HyperSmooth 6.0, and HDR photo.",
        createdAt: "2025-09-13"
    },
    {
        id: 15,
        shopId: 7,
        name: "PlayStation 5 Slim",
        price: 499,
        oldPrice: 599,
        image: "../asset/img/home/ps5Slim.jpg",
        category: "gaming",
        rating: 4.8,
        reviews: 640,
        stock: 30,
        description: "Slimmer PS5 with 1TB SSD, DualSense controller, and ray tracing graphics.",
        createdAt: "2025-11-10"
    },
    {
        id: 16,
        shopId: 9,
        name: "Xbox Series X",
        price: 489,
        oldPrice: 569,
        image: "../asset/img/home/xBox.webp",
        category: "gaming",
        rating: 4.7,
        reviews: 472,
        stock: 28,
        description: "The fastest, most powerful Xbox with 12 teraflops of processing power and 1TB SSD.",
        createdAt: "2025-11-10"
    },
    {
        id: 17,
        shopId: 9,
        name: "Nintendo Switch OLED",
        price: 329,
        oldPrice: 379,
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/n/i/nintendo-switch-oled_1.png",
        category: "gaming",
        rating: 4.8,
        reviews: 558,
        stock: 55,
        description: "Vibrant 7-inch OLED screen, 64GB storage, and enhanced audio for handheld gaming.",
        createdAt: "2025-10-08"
    },
    {
        id: 18,
        shopId: 8,
        name: "Anker 737 Power Bank",
        price: 139,
        oldPrice: 179,
        image: "https://cdn2.cellphones.com.vn/x/media/catalog/product/p/i/pin-sac-du-phong-anker-737-powercore-24000-140w-a1289_8__1.png",
        category: "smartphone",
        rating: 4.5,
        reviews: 203,
        stock: 70,
        description: "24,000mAh portable charger with 140W output and smart digital display.",
        adminStatus: "rejected",
        createdAt: "2025-08-15"
    },
    {
        id: 19,
        shopId: 8,
        name: "Logitech MX Master 3S",
        price: 99,
        oldPrice: 129,
        image: "../asset/img/home/logiMX.jpg",
        category: "smartphone",
        rating: 4.7,
        reviews: 431,
        stock: 80,
        description: "Ergonomic wireless mouse with 8K DPI tracking, quiet clicks, and MagSpeed scroll.",
        createdAt: "2025-06-20"
    },
    {
        id: 20,
        shopId: 8,
        name: "Kindle Paperwhite 11th Gen",
        price: 149,
        oldPrice: 189,
        image: "../asset/img/home/kindle.jpeg",
        category: "smartphone",
        rating: 4.6,
        reviews: 356,
        stock: 90,
        description: "6.8-inch glare-free display, adjustable warm light, and 10 weeks of battery life.",
        createdAt: "2025-10-25"
    },
    {
        id: 21,
        shopId: 5,
        name: "Apple AirPods Pro 2",
        price: 249,
        oldPrice: 299,
        image: "https://cdn.tgdd.vn/Products/Images/54/289700/s16/apple-airpods-pro-gen-2-trang-650x650.jpg",
        category: "audio",
        rating: 4.8,
        reviews: 624,
        stock: 80,
        description: "Active noise cancellation, Adaptive Transparency, and Personalized Spatial Audio with dynamic head tracking.",
        adminStatus: "approved",
        createdAt: "2025-09-22"
    },
    {
        id: 22,
        shopId: 5,
        name: "iPad Air M2",
        price: 749,
        oldPrice: 899,
        image: "https://cdsassets.apple.com/live/7WUAS350/images/tech-specs/ipad-air-m2-blue-wifi-select.png",
        category: "laptops",
        rating: 4.7,
        reviews: 312,
        stock: 25,
        description: "Powerful M2 chip, brilliant 10.9-inch Liquid Retina display, and all-day battery in a thin, light design.",
        adminStatus: "approved",
        createdAt: "2025-03-08"
    },
    {
        id: 23,
        shopId: 7,
        name: "Garmin Fenix 7S",
        price: 649,
        oldPrice: 799,
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/a/garmin-fenix-7s-sapphire-solar_2.jpg",
        category: "wearables",
        rating: 4.8,
        reviews: 178,
        stock: 15,
        description: "Multisport GPS watch with solar charging, advanced health monitoring, and 11-day battery life.",
        adminStatus: "approved",
        createdAt: "2025-05-20"
    },
    {
        id: 24,
        shopId: 9,
        name: "DJI Mini 4 Pro",
        price: 759,
        oldPrice: 959,
        image: "https://cdn2.fptshop.com.vn/unsafe/512x0/filters:format(webp):quality(75)/2023_10_25_638341026619614700_dji-mini-4-pro-fly-more-combo.jpg",
        category: "cameras",
        rating: 4.9,
        reviews: 219,
        stock: 12,
        description: "Compact drone with 4K/60fps HDR video, omnidirectional obstacle sensing, and 34-minute flight time.",
        adminStatus: "approved",
        createdAt: "2025-10-25"
    },
    {
        id: 25,
        shopId: 8,
        name: "Razer Blade 16",
        price: 2499,
        oldPrice: 2999,
        image: "https://cdn2.fptshop.com.vn/unsafe/512x0/filters:format(webp):quality(75)/2024_3_14_638459971533461985_razer-blade-16-2024-1.jpg",
        category: "laptops",
        rating: 4.7,
        reviews: 95,
        stock: 8,
        description: "16-inch gaming laptop with Intel Core i9-14900HX, RTX 4090, and dual-mode OLED display.",
        adminStatus: "approved",
        createdAt: "2025-01-15"
    },
    {
        id: 26,
        shopId: 6,
        name: "OnePlus 12",
        price: 799,
        oldPrice: 999,
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/n/oneplus-12-5g-xanh-1.png",
        category: "smartphone",
        rating: 4.6,
        reviews: 243,
        stock: 35,
        description: "Snapdragon 8 Gen 3, Hasselblad triple camera, 100W SUPERVOOC charging, and 5400mAh battery.",
        adminStatus: "approved",
        createdAt: "2025-02-10"
    },
    {
        id: 27,
        shopId: 7,
        name: "Nikon Z6 III",
        price: 1999,
        oldPrice: 2499,
        image: "https://cdn2.fptshop.com.vn/unsafe/512x0/filters:format(webp):quality(75)/2024_7_5_638559329671178000_nikon-z6-iii-1.jpg",
        category: "cameras",
        rating: 4.8,
        reviews: 87,
        stock: 10,
        description: "Partially-stacked full-frame sensor, 6K ProRes RAW video, and 20fps continuous burst shooting.",
        adminStatus: "approved",
        createdAt: "2025-07-05"
    },
    {
        id: 28,
        shopId: 9,
        name: "ASUS ROG Ally X",
        price: 799,
        oldPrice: 999,
        image: "https://cdn2.fptshop.com.vn/unsafe/512x0/filters:format(webp):quality(75)/2024_6_3_638527327785406041_asus-rog-ally-x-1.jpg",
        category: "gaming",
        rating: 4.7,
        reviews: 156,
        stock: 20,
        description: "Handheld gaming PC with AMD Ryzen Z1 Extreme, 7-inch 120Hz display, and Windows 11.",
        adminStatus: "approved",
        createdAt: "2025-06-03"
    }
];
